Prof 3 pwd candidate
w3c/dxwg pull request #1074
Opened 2019-09-13 06:54 UTC by nicholascar

2019-09-13 07:59 UTC, rob-metalinkage requested changes
That a lot of editorial changes - at least in separate commits.  There are a few grammar fixes needed on section on constraints and I think the property chain axiom is a substantive change - I'd rather have the removed and in a separate PR as there is an active issue discussing this and its the only change to the model in this PR.

2019-09-15 05:25 UTC, nicholascar commented
Following a discussion with @rob-metalinkage: I've marked the axiom a "feature at risk" with an issue (#1078) since it's the substantive addition in this PR. With it marked as at risk (in two places: the Introduction and at the point of definition in the Specification), it can be included now and removed from the CR if indeed it becomes problematic.

2019-09-16 15:36 UTC, aisaac commented
I'm trying to go through the pile of changes....
@nicholascar @rob-metalinkage why is the Requirements appendix removed? The note says it's redundant. What replaced it?

2019-09-16 16:21 UTC, nicholascar commented
@aisaac the Requirements Appendix was meant to be a list of Requirements & responses to them, see https://www.w3.org/TR/dx-prof/#requirements. However, we didn't use that approach much preferring instead to place Issues in the doc and deal with their implications via PRs. So the Requirements listing was just a method that was outside of our editing processes. 

For the Requirements that were directly from the UCR, we listed them elsewhere: https://www.w3.org/TR/dx-prof/#motivating-requirements.

I think we should go back and check off against UCR requirements, especially to check what Guidance need not do, but we just don't need the listing as we had it in this appendix in 2PWD.

2019-09-16 19:38 UTC, aisaac commented
@nicholascar ok I think I was lead on the wrong track by the note saying 'duplicate'. 'obsolete' would have been more precise!

2019-09-16 19:50 UTC, aisaac commented
For the record I'm lukewarm on the change to the "family of documents" section. But well I guess that you had to adapt. and we can still tweak it depending on what happens in the coming two months.
I would argue for removing the typio on "This document is one from set of documents on profiles" though. It's "This document is one from a set of documents on profiles"!

2019-09-16 19:58 UTC, aisaac commented
Big typo in the intro on "A specification is "A basis for comparison; a reference point against which other things can be evaluated." (see the definition below) and a A profile, such as a profile or perhaps an application profile, is defined as "A [data/application] specification that constrains, extends, combines, or provides guidance or explanation about the usage of other [data/application] specifications""

2019-09-16 20:04 UTC, aisaac commented
There's going to be a lot of push-back if the definitions do not exactly represent the agreement at #963. And I'm probably going to be part of it. The formal disappearance of the definition of "data profile" (even if you tried to provide a workable alternative) is going to trigger a lot of discussions. Some of them already happened earlier (I don't know in which issue). I am far from convinced that representing a more general view on profiles is worth jeopardizing the spec and firing up all these discussions. The more general view could be added on top of that, at a later stage.

2019-09-16 20:09 UTC, aisaac commented
For the record, I am **not** reviewing the sections on related work. I have no time checking the amount of text, I've made (or would make) comments as part of other issues. And I believe that whatever text (minus typos of course!) is worth sharing with the group at this stage.

2019-09-16 20:12 UTC, aisaac commented
I believe there's a typo on "that is derived from, but separate to, the namespace for PROF". "separate" is also to be used with "from", isn't it?

2019-09-16 20:21 UTC, aisaac commented
I'm not sure why 521, 507, 802, 453, 795 are not mentioned in the doc anymore. As long as they remain open on github while they're under discussion, that's fine, but this makes it less clear, what's the rationale for having issues referenced or not in the document.

2019-09-16 20:27 UTC, aisaac commented
In 6.8 Repetition in "Constraint Languages are frequently used in profile profile definitions"

2019-09-16 20:34 UTC, aisaac requested changes
OK I've reviewed what I could review. All comments that I think could (some should) be addressed are now above!

2019-09-16 20:38 UTC, aisaac commented
I forgot to say - impressive work, @nicholascar !

2019-09-16 21:45 UTC, kcoyle commented
There seems to be content here that is not resolved in issues. For example, @aisaac are you satisfied with the resolution of "prof:isTransitiveProfileOf needs more convincing case and/or example #643"? Also, we have: "Improve defintion of prof:isTransitiveProfileOf #1071", "Suggested updates to definition of PROF constructs #1061" not to mention about 80 other open issues. What is being proposed for all of the open issues that are not considered "at risk"?

2019-09-16 21:52 UTC, aisaac commented
@kcoyle I think it is ok to have a PR doing things not in issues, and not tackling all open issues. There could be another later PWD candidate to address the open issues, for sure. Maybe it's already in preparation. This PR is already big; I think in general they should be more granular.

2019-09-16 22:15 UTC, kcoyle commented
Regarding the definition of profiles (for this and for the conneg document), the approved language is:

>Data Profile

>A data specification that constrains, extends, combines, or provides
guidance or explanation about the usage of other data specifications.

>Data Specification

>A specification, with human- and/or machine-processable representations,
that defines the content and structure of data used in a given context.

While it probably makes sense to say in the definitions area that the word "profile" will be used in the document to mean what is defined as "data profile", the group did vote to define the term as "data profile."

2019-09-16 22:56 UTC, kcoyle commented
@aisaac You may have missed the information on the deadline. The date and time of tomorrow's meeting is the final deadline for a CR-ready version of PROF and of conneg. There will not be additional "PRs" except in support of a Working Group note. That is why I am questioning the disposition of open issues. I'm trying to understand whether this version is considered final or if the editors are planning to continue the work as a note.

2019-09-17 00:24 UTC, rob-metalinkage commented
The PR is not addressing the definitions - thats a substantive change that needs to be isolated to a separate PR. I think the problem is in the title - i'll rename it..  
Fix up typos and grammar for now - dont change scope of this PR.  This will help reviewing PRs with the substantive changes.

2019-09-17 09:04 UTC, aisaac commented
Thanks for the clarification @rob-metalinkage . @kcoyle this was indeed my approach when looking at this PR. Not requiring that it does everything. In fact I implicitly said earlier to @nicholascar that it would be great if we would stop piling things in here, because otherwise I can't review them :-)

2019-09-17 10:47 UTC, nicholascar commented
@aisaac I've addressed 4 of your comments requesting changes (see commits above linking to comment IDs) and regarding https://github.com/w3c/dxwg/pull/1074#issuecomment-531942290 (Issues removed): 

* #521 - the proponant (Rob) is happy for this to be added as Future Work and a poll so far indicates watching participants' agreement so I thought it would serve no purpose to leave in the doc. We should address it, and all other future-work tagged issues after PWD release
* #507 - duplicate for the now "at risk" issue (#1078) in the doc which I added to highlight the proposed axiom. There are about 4 issues that all get at the same thing
* #802 - one of the semi-duplicates for the above. The axiom answers the question so if it's accepted then this Issue is for Guidance (which I think is the right place for it)
* #453 - this has been addressed in a commit above, as per your request. I thought it would be so I'd like to see the PR pulled through to ED so I can tag the Issue as due-for-closing. Seems onerous to keep back-and-forth tagging (chicken and egg)
* #795 - I think this is now well addressed by the isTransitiveProfileOf semantics (linked to above) and the axiom so I've taken it out of this PR. I will reference the proposed solution, and the example in the doc from SKOS as per Karen's comment in the Issue, in an email to the ShEx group that raised it.

2019-09-17 11:09 UTC, aisaac approved these changes
OK @nicholascar thanks for the explanation and the last edits which indeed fix the typos that I had found and revert the definition to the official one.

And I agree with removing the reference to the couple of issues you flag as "(near-)duplicates". Even if they are still open, the document makes reference to "nearby" issues. It would be confusing to point the reader to all the issues in our web - it's already quite difficult for ourselves...

2019-09-17 13:36 UTC, rob-metalinkage approved these changes

2019-09-17 13:36 UTC, merged