DatasetSeries: adding dcat:inSeries and its inverse, updating the  dataset examples.
w3c/dxwg pull request #1328
Opened 2021-03-14 18:35 UTC by riccardoAlbertoni

Updating the PR #1292 on dataset series to include the result of the discussion we had in issue #1307 

This  PR replaces `dcterms:isPartOf`  and its inverse `dcterms:hasPart` with `dcat:inSeries` and its inverse `dcat:hasSeriesMember`.

Some people insist on keeping both directions,  and the examples in #1292 are using both `dcterms:isPartOf`  and its inverse `dcterms:hasPart`,  so for the moment,  the PR maintains both directions. 

DIFF with  PR #1292

2021-03-14 19:02 UTC, andrea-perego commented
For the inverse of `dcat:inSeries` I suggest we use something shorter: `dcat:hasMember`.

Another option for the names of these properties is `dcat:hasParent` / `dcat:hasChild` , following the terminology used in ISO 19115 for dataset series.

2021-03-15 03:13 UTC, dr-shorthair commented
Need to add `inSeries` to the list of properties added to `dcat:Dataset`

2021-03-15 03:16 UTC, dr-shorthair requested changes
Need to add `inSeries` to the list of properties added to `dcat:Dataset` (in the intro text on Dataset section)

2021-03-15 11:03 UTC, riccardoAlbertoni commented
> Need to add `inSeries` to the list of properties added to `dcat:Dataset` (in the intro text on Dataset section)

Thanks,  done.

2021-03-15 11:12 UTC, dr-shorthair approved these changes

2021-03-15 11:25 UTC, riccardoAlbertoni commented
> For the inverse of `dcat:inSeries`, I suggest we use something shorter: `dcat:hasMember.`
> 
> Another option for the names of these properties is `dcat:hasParent` / `dcat:hasChild` , following the terminology used in ISO 19115 for dataset series.

@andrea-perego:
Yes, the names are long. However, I wonder if mentioning 'series' in the property names can help recall and use these properties more coherently. This also considering possible confusion with `dcterms:hasPart` and other parts-related properties.  What do you think?

2021-03-15 14:47 UTC, andrea-perego commented
> @andrea-perego:
> Yes, the names are long. However, I wonder if mentioning 'series' in the property names can help recall and use these properties more coherently. This also considering possible confusion with `dcterms:hasPart` and other parts-related properties. What do you think?

I don't think it's necessary to recall the scope of this property, as it has its own domain (`dcat:DatasetSeries`). For the same reason, including "series" in the property name looks redundant, and I am not very worried about being confused with `dcterms:hasPart`.

However, if the close semantics of "part" and "series" raises concerns on improper use, we should consider other options.

`dcat:hasChild` / `dcat:hasParent` are a good alternative, IMO, and they reflect the hierarchical structure of dataset series, as already mentioned in PR https://github.com/w3c/dxwg/pull/1292 and in https://github.com/w3c/dxwg/issues/1307#issuecomment-799139402

2021-03-15 16:33 UTC, riccardoAlbertoni commented
> > @andrea-perego:
> > Yes, the names are long. However, I wonder if mentioning 'series' in the property names can help recall and use these properties more coherently. This also considering possible confusion with `dcterms:hasPart` and other parts-related properties. What do you think?
> 
> I don't think it's necessary to recall the scope of this property, as it has its own domain (`dcat:DatasetSeries`). For the same reason, including "series" in the property name looks redundant, and I am not very worried about being confused with `dcterms:hasPart`.
> 
> However, if the close semantics of "part" and "series" raises concerns on improper use, we should consider other options.
> 
> `dcat:hasChild` / `dcat:hasParent` are a good alternative, IMO, and they reflect the hierarchical structure of dataset series, as already mentioned in PR #1292 and in [#1307 (comment)](https://github.com/w3c/dxwg/issues/1307#issuecomment-799139402)

If you think `dcat:hasSeriesMember` is too long and not acceptable then `dcat:hasMember` will be my choice.

Using `dcat:hasChild` and `dcat:hasParent` helps those familiar with ISO dataset series.  However, we target a larger audience. In this target, I suspect people might have different views of what is considered a child of a dataset (potentially, anything originated by a dataset can be considered a 'child'!? and that might be confusing).

2021-03-16 20:28 UTC, riccardoAlbertoni commented
I am going to merge this with dcat-dataseries-issue1272  PR #1292  so that we have only one updated version for the dataset series as having two seems confusing commenters.  We still need to decide the property name between series and dataset (i.e., if we used dcat:hasSeriesMember or dcat:hasMember), but it is an adjustment we can do later, in PR #1292.

2021-03-16 20:28 UTC, merged