Dcat issue 1364 second solution
w3c/dxwg pull request #1379
Opened 2021-06-07 17:10 UTC by riccardoAlbertoni

Alternative solution to PR #  
Considering that dcterm:subject has been recently changed to let both literals and  URI,  by defining dcat:thems as an owl:ObjectProperty  and dropping the dcat:theme's range,  dcat:theme would still restrict dcterms:subject to URIs,  while dcat:keyword might restrict dcterms:subject to literals.

This would also limit the automatic inference of skos:Concept, which could be potentially problematic when applied to instances whose classes are defined disjoint from skos:Concept.

2021-06-07 20:13 UTC, dr-shorthair commented
This looks clean and sensible to me

2021-06-18 14:41 UTC, riccardoAlbertoni commented
@andrea-perego  can you check the rephasing of the note before defining`dcat:theme` meets the expectation you have expressed in the last DCAT teleconference?  Feel free to rephrase it, otherwise. Thanks.

2021-06-20 09:38 UTC, andrea-perego requested changes
Thanks, @riccardoAlbertoni .

+1 from me. I just suggested an editorial change.

2021-06-20 09:38 UTC, andrea-perego commented on dcat/index.html
> +                <tr><th>OWL Object Property:</th><td><a href="http://www.w3.org/ns/dcat#theme"><code>dcat:theme</code></a></td></tr>
```suggestion
                <tr><th>RDF Property:</th><td><a href="http://www.w3.org/ns/dcat#theme"><code>dcat:theme</code></a></td></tr>
                <tr><th>Type:</th><td><a href="http://www.w3.org/2002/07/owl#ObjectProperty"><code title="http://www.w3.org/2002/07/owl#ObjectProperty">owl:ObjectProperty</code></a></td></tr>```

2021-06-21 09:33 UTC, riccardoAlbertoni commented
> Thanks, @riccardoAlbertoni .
> 
> +1 from me. I just suggested an editorial change.

Thanks, Andrea. I have accepted your suggestion.

2021-06-21 10:16 UTC, andrea-perego approved these changes

2021-06-23 09:47 UTC, riccardoAlbertoni commented
@davebrowning , @pwin , @agbeltran , Is this PR ok for you?

2021-06-23 15:29 UTC, davebrowning approved these changes

2021-06-23 15:55 UTC, merged