DCAT updating change history
w3c/dxwg pull request #1476
Opened 2022-03-16 17:48 UTC by riccardoAlbertoni

This PR contributes to #1471
Updated the history adding items for issues  1472 and 1335. 

I wouldn't add to the change history details related to issues 1429, 1440, 1431, 1455, would you?

2022-03-16 20:48 UTC, andrea-perego requested changes
Proposed changes:
- Refer to the updated class diagram with the relevant cross-reference
- Editorial fix

2022-03-16 20:48 UTC, andrea-perego commented on dcat/index.html
> + <p>Update class diagram in figure 1 according to Issue <a href="https://github.com/w3c/dxwg/issues/#1470">#1470</a>.</p>
```suggestion
 <p>Update class diagram in <a href="#fig-dcat-all-attributes"></a> according to Issue <a href="https://github.com/w3c/dxwg/issues/#1470">#1470</a>.</p>
```

2022-03-16 20:48 UTC, andrea-perego commented on dcat/index.html
> +<p>Added <code>dcat:seriesMember</code> as the inverse of <a href="#Property:dataset_in_series"><code>dcat:inSeries</code></a> in section <a href='#inverse-properties'></a> - see Issue <a href="https
```suggestion
<p>Added property <code>dcat:seriesMember</code> as the inverse of <a href="#Property:dataset_in_series"><code>dcat:inSeries</code></a> in section <a href="#inverse-properties"></a> - see Issue <a href="https://github.com/w3c/dxwg/issues/1335">#1335</a>.</p>
```

2022-03-16 21:02 UTC, andrea-perego commented
@riccardoAlbertoni said:

> This PR contributes to #1471
> 
> Updated the history adding items for issues #1472 and #1335.
> 
> I wouldn't add to the change history details related to issues #1429, #1440, #1431, #1455, would you?

Yes, maybe it is not necessary.

BTW, the changelog already includes a reference to #1440.

2022-03-16 22:51 UTC, andrea-perego requested changes
Editorial fix - sorry, I missed it.

2022-03-16 22:51 UTC, andrea-perego commented on dcat/index.html
> + <p>Update class diagram in <a href="#fig-dcat-all-attributes"></a> according to Issue <a href="https://github.com/w3c/dxwg/issues/#1470">#1470</a>.</p>
```suggestion
 <p>Updated class diagram in <a href="#fig-dcat-all-attributes"></a> according to Issue <a href="https://github.com/w3c/dxwg/issues/#1470">#1470</a>.</p>
```

2022-03-17 07:39 UTC, agbeltran approved these changes

2022-03-22 18:02 UTC, riccardoAlbertoni commented
> @riccardoAlbertoni said:
> 
> > This PR contributes to #1471
> > Updated the history adding items for issues #1472 and #1335.
> > I wouldn't add to the change history details related to issues #1429, #1440, #1431, #1455, would you?
> 
> Yes, maybe it is not necessary.
> 
> BTW, the changelog already includes a reference to #1440.

@andrea-perego,  the above suggestion  are implemented via PR #1484

2022-03-22 22:25 UTC, andrea-perego approved these changes

2022-03-22 22:25 UTC, merged