UPDATES rdf according to #1466 and #1470
w3c/dxwg pull request #1482
Opened 2022-03-21 18:41 UTC by riccardoAlbertoni

2022-03-22 17:30 UTC, riccardoAlbertoni commented
This PR closes #1483 by deleting rdfs:members as discussed

2022-03-22 18:33 UTC, andrea-perego requested changes
Thanks for taking care of this, @riccardoAlbertoni . Only found a minor editorial fix to be done.

2022-03-22 18:33 UTC, andrea-perego commented on dcat/rdf/dcat3.ttl
> +  dcterms:modified "2022-03-21"^^xsd:date ;
```suggestion
  dcterms:modified "2022-03-22"^^xsd:date ;
```

2022-03-22 22:28 UTC, andrea-perego approved these changes

2022-03-26 16:05 UTC, davebrowning approved these changes

2022-03-26 16:25 UTC, merged