Adding aligment to sdo:CreativeWorkSeries
w3c/dxwg pull request #1501
Opened 2022-04-10 18:46 UTC by agbeltran

2022-04-19 07:05 UTC, dr-shorthair approved these changes
`next` and `previous` missing from Schema.org. Looks like a hole. Perhaps we should comment there? 

https://github.com/schemaorg/schemaorg/issues/3093

2022-04-30 17:31 UTC, andrea-perego requested changes
Thanks for preparing this update, @agbeltran .

Probably we should also add the mapping between [`dcat:version`](https://w3c.github.io/dxwg/dcat/#Property:resource_version) and [`sdo:version`](https://schema.org/version). This could be included right after the mapping of `dcat:contactPoint` under `dcat:Resource`.

I can take care of this, if you agree, @agbeltran .

2022-04-30 17:36 UTC, andrea-perego requested changes
I've just realised that there is an error: `dcat:inSeries` must go under `dcat:Dataset`, and not `dcat:DatasetSeries`.

2022-04-30 21:13 UTC, andrea-perego approved these changes
@agbeltran , I've moved `dcat:inSeries` under `dcat:Dataset` and added `dcat:version`. I've also moved up `dcat:DatasetSeries` - see https://github.com/w3c/dxwg/pull/1501/commits/fd9dc16956b2660764bdb11efa1e769a45e60d12

Please check if you're happy with the changes.

2022-05-02 10:49 UTC, agbeltran commented
thanks @andrea-perego - looks good, will merge

2022-05-02 10:49 UTC, merged