Adding information on new features for DCAT 3 and prioritization
w3c/dxwg pull request #1531
Opened 2022-09-05 16:52 UTC by riccardoAlbertoni

This PR integrates the DCAT 3 Explainer adding information on new features for DCAT 3 and prioritization as required #1530. 

Please check if other important matters need to be mentioned.

2022-09-07 14:41 UTC, riccardoAlbertoni commented
Please consider the current version of the explainers. It should be coherent with the discussion we had in yesterday's DCAT call, but feel free to suggest changes or propose to omit any information if you think the changes are too lengthy.

We will reply about the usage of RDF lists separately.

2022-09-07 19:07 UTC, andrea-perego approved these changes

2022-09-12 19:35 UTC, agbeltran requested changes

2022-09-12 19:35 UTC, agbeltran commented on docs/explainer.md
> +- they counted a quite conspicuous number of open issues, 14 and 18 open issues, respectively
did you mean conspicuous or copious?

2022-09-12 19:35 UTC, agbeltran commented on docs/explainer.md
> +Of course, we didn't work only on Dataset series and Versioning,
I would change this sentence to: "In addition to Dataset series and Versioning, we also worked on other issues".

2022-09-12 19:35 UTC, agbeltran commented
thanks @riccardoAlbertoni - I pushed a couple of minor changes, and left a couple of text suggestions for your consideration.

2022-09-13 10:05 UTC, riccardoAlbertoni commented on docs/explainer.md
> +- they counted a quite conspicuous number of open issues, 14 and 18 open issues, respectively
Both are fine for me.

2022-09-13 10:09 UTC, riccardoAlbertoni reviewed
Accepting Alejandra's suggestions

2022-09-13 10:09 UTC, riccardoAlbertoni commented on docs/explainer.md
> +- they counted a quite conspicuous number of open issues, 14 and 18 open issues, respectively
```suggestion
- they counted a quite copious number of open issues, 14 and 18 open issues, respectively
```

2022-09-13 10:09 UTC, riccardoAlbertoni commented on docs/explainer.md
> +Of course, we didn't work only on Dataset series and Versioning,
Fine to me
```suggestion
In addition to Dataset series and Versioning, we also worked on other issues,
```

2022-09-13 10:11 UTC, riccardoAlbertoni commented
@agbeltran  I have accepted your requests for changes.
Please, unlock the PR merging if you don't have any other observations.

2022-09-13 10:12 UTC, riccardoAlbertoni commented on docs/explainer.md
> +In addition to Dataset series and Versioning, we also worked on other issues,
```suggestion
In addition to Dataset series and Versioning, we also worked on other issues.
```

2022-09-13 10:19 UTC, agbeltran approved these changes

2022-09-13 10:21 UTC, merged