Adjusting usage note dcterms:language
w3c/dxwg pull request #1535
Opened 2022-09-28 10:44 UTC by riccardoAlbertoni

This PR changes a Usage Note for <code>dcterms:language</code> in <code>dcat:Resource</code>
Considering the questions in issue #1532, we might want to be more explicit, suggesting that distribution can be multilingual.

2022-09-28 18:54 UTC, andrea-perego requested changes
@riccardoAlbertoni , probably, instead of modifying the existing usage note, we should just add a sentence to cover the case of multilingual distributions - something like:

> In case of multilingual distributions, the distributions will have multiple <code>dcterms:language</code> values.

2022-10-02 08:48 UTC, davebrowning reviewed
I'd vote for the addition @andrea-perego suggested.   It seems clearer to me!

2022-10-03 08:03 UTC, riccardoAlbertoni commented
I agree that adding Andrea's sentence is clearer. I will modify the PR accordingly.

2022-10-03 08:06 UTC, riccardoAlbertoni commented on dcat/index.html
> +                <tr><th class="prop">Usage note:</th><td>If representations of a dataset are available for each language or group of languages separately, define an instance of <code>dcat:Distributio
```suggestion
                <tr><th class="prop">Usage note:</th><td>If representations of a dataset are available for each language separately, define an instance of <code>dcat:Distribution</code> for each language and describe the specific language of each distribution using <code>dcterms:language</code> (i.e., the dataset will have multiple <code>dcterms:language</code> values and each distribution will have just one as the value of its <code>dcterms:language</code> property). In case of multilingual distributions, the distributions will have multiple <code>dcterms:language</code> values.</td></tr>
```

2022-10-03 10:06 UTC, andrea-perego approved these changes

2022-10-03 10:08 UTC, andrea-perego commented
Thanks, @riccardoAlbertoni . I think we also need to update the changelog and the ack section.

2022-10-03 10:11 UTC, andrea-perego commented
> Thanks, @riccardoAlbertoni . I think we also need to update the changelog and the ack section.

Just updated the ack section via commit https://github.com/w3c/dxwg/pull/1535/commits/5f358e6d52b2848cb31fc7325e4bdc508badcbf8

2022-10-03 10:21 UTC, andrea-perego commented
> Thanks, @riccardoAlbertoni . I think we also need to update the changelog and the ack section.

Changelog updated via commit https://github.com/w3c/dxwg/pull/1535/commits/d179d13a29f726220427e74b3de6c406bbf16bcd

2022-10-06 10:14 UTC, riccardoAlbertoni commented
Thanks, @andrea-perego. 
The DIFF is available at https://services.w3.org/htmldiff?doc1=https://w3c.github.io/dxwg/dcat/&doc2=https://raw.githack.com/w3c/dxwg/dcat-issue-1532/dcat/index.html

@davebrowning or other editors: could you accept the PR?

2022-10-07 17:10 UTC, andrea-perego commented
@riccardoAlbertoni , I made an editorial fix to avoid that abstract and sotd sections are included in the ToC - see commit https://github.com/w3c/dxwg/pull/1535/commits/f22e792e118d1efc11f48cbb29119e49c5d4bea9

2022-10-08 08:24 UTC, davebrowning approved these changes

2022-10-08 08:24 UTC, merged