Removing DCAT 2 leftover
w3c/dxwg pull request #1556
Opened 2023-02-03 18:31 UTC by riccardoAlbertoni

Closes #1519

2023-02-03 18:44 UTC, riccardoAlbertoni commented
Other aspects we might want to consider to deal with:

- the ranges of `dcat:theme` and dcat:themeTaxonomy have been  relaxed, do we want to mirror that in fig1?

2023-02-06 16:47 UTC, riccardoAlbertoni commented
This PR is ready for being  reviewed.  I have created a separate issue #1557  for 
> * the ranges of `dcat:theme` and dcat:themeTaxonomy have been  relaxed, do we want to mirror that in fig1?

2023-02-07 01:13 UTC, dr-shorthair commented on dcat/index.html
> +        In order to support data citation, this DCAT 2 added the consideration of <a href="#dereferenceable-identifiers">dereferenceable identifiers</a> and support for indicating
delete `this`

2023-02-07 01:13 UTC, dr-shorthair commented on dcat/index.html
> +      <p>Often datasets are associated with publications (scholarly articles, reports, etc.) and DCAT relies on the property <a href="#Property:resource_is_referenced_by"><code>dcterms:isReferencedBy
`Datasets are often` would be better

2023-02-07 01:15 UTC, dr-shorthair requested changes
Two minor wording changes suggested

2023-02-07 16:09 UTC, davebrowning requested changes
I think its worthwhile making the suggested changes (especially the first one). [I can do it if you agree..?]

2023-02-07 16:34 UTC, riccardoAlbertoni commented on dcat/index.html
> +        In order to support data citation, this DCAT 2 added the consideration of <a href="#dereferenceable-identifiers">dereferenceable identifiers</a> and support for indicating
```suggestion
        In order to support data citation, DCAT 2 added the consideration of <a href="#dereferenceable-identifiers">dereferenceable identifiers</a> and support for indicating
```

2023-02-07 16:35 UTC, riccardoAlbertoni commented on dcat/index.html
> +      <p>Often datasets are associated with publications (scholarly articles, reports, etc.) and DCAT relies on the property <a href="#Property:resource_is_referenced_by"><code>dcterms:isReferencedBy
```suggestion
      <p>Datasets are often associated with publications (scholarly articles, reports, etc.) and DCAT relies on the property <a href="#Property:resource_is_referenced_by"><code>dcterms:isReferencedBy</code></a> to provide a way to link publications about a dataset to the dataset</p>
```

2023-02-07 16:40 UTC, riccardoAlbertoni commented
Changes asked by @davebrowning and @dr-shorthair have been included.

2023-02-07 16:56 UTC, davebrowning approved these changes

2023-02-07 22:28 UTC, dr-shorthair approved these changes

2023-02-07 22:28 UTC, merged