Editorial chances to pushish pr
w3c/dxwg pull request #1597
Opened 2024-04-22 12:44 UTC by riccardoAlbertoni

Some Editorial changes to consider when pushing the ED as PR.
- updating obvious references to the status of the document 
- removing "features at risk" as   existing implementations for them are included in the report https://w3c.github.io/dxwg/dcat3-implementation-report/

I'm not sure when this Pull Request needs to be merged; I guess after the group vote for moving to PR might be a good time. 

@pchampin and all the editors, what do you think?

2024-04-22 13:12 UTC, andrea-perego commented
@riccardoAlbertoni said:

> I'm not sure when this Pull Request needs to be merged; I guess after the group vote for moving to PR might be a good time.

I'm not sure if it should be actually merged into the `gh-pages` branch. The ED is meant to stay, and shouldn't be overwritten. Am I wrong?

2024-05-08 15:55 UTC, pchampin requested changes

2024-05-08 15:55 UTC, pchampin commented on dcat/config.js
> +  specStatus: "PR",
```suggestion
  specStatus: "ED",
```
Since this will reflect automatically on the "live" version of the document on github pages, this should not be changed here.
Once the rest of this PR is merged, I will generate a publication snapshot with the correct option.

2024-05-08 17:48 UTC, riccardoAlbertoni commented
@pchampin wrote 
>Since this will reflect automatically on the "live" version of the document on github pages, this should not be changed here.
Once the rest of this PR is merged, I will generate a publication snapshot with the correct option.

Following @andrea-perego and @pchampin's comments, we need to drop the parts mentioning "features at risk," but we do not need to change the config stuff to prepare the actual PR. Pierre-Antoine will deal with the latter.
Having accepted Pierre-Antoine's latest suggestions, we should be ready to merge this Pull Request to the live editorial draft.

Please check  the following
[document preview](https://raw.githack.com/w3c/dxwg/EditorialChancesForMovingToPR/dcat/index.html)
[document diff](https://services.w3.org/htmldiff?doc1=https://w3c.github.io/dxwg/dcat/&doc2=https://raw.githack.com/w3c/dxwg/EditorialChancesForMovingToPR/dcat/index.html)

2024-05-13 14:03 UTC, andrea-perego approved these changes

2024-05-22 19:38 UTC, pchampin approved these changes

2024-05-22 19:39 UTC, merged