adding History of changes since CR
w3c/dxwg pull request #1604
Opened 2024-05-24 16:26 UTC by riccardoAlbertoni

Adding the new history section to track the changes since CR publication.

2024-05-24 22:59 UTC, davebrowning approved these changes

2024-05-25 08:08 UTC, andrea-perego requested changes
Some editorial fixes.

2024-05-25 08:08 UTC, andrea-perego commented on dcat/index.html
> +<p>Editorial fixes as suggested in issues <a href="https://github.com/w3c/dxwg/issues/1581">#1581</a>, <a href="https://github.com/w3c/dxwg/issues/1583">#1583</a>, <a href="https://github.com/w3c/dxw
```suggestion
<p>Editorial fixes as suggested in Issues <a href="https://github.com/w3c/dxwg/issues/1581">#1581</a>, <a href="https://github.com/w3c/dxwg/issues/1583">#1583</a>, <a href="https://github.com/w3c/dxwg/issues/1591">#1591</a>.</p>
```

2024-05-25 08:08 UTC, andrea-perego commented on dcat/index.html
> +    <li><p>Fixed the wrong link to spdx 2.2 - see issue <a href="https://github.com/w3c/dxwg/issues/1592">#1592</a>.</p></li>
```suggestion
    <li><p>Fixed the wrong link to SPDX 2.2 - see Issue <a href="https://github.com/w3c/dxwg/issues/1592">#1592</a>.</p></li>
```

2024-05-25 08:10 UTC, andrea-perego approved these changes

2024-05-27 09:51 UTC, davebrowning approved these changes

2024-05-27 10:23 UTC, merged