Conneg fpwd edits
w3c/dxwg pull request #593
Opened 2018-11-16 00:05 UTC by nicholascar

2018-11-16 16:19 UTC, larsgsvensson approved these changes

2018-11-16 16:21 UTC, larsgsvensson approved these changes
Addressing Issue 575.1 OK

2018-11-16 16:23 UTC, larsgsvensson approved these changes
Addressing Issue 575.4 OK

2018-11-16 16:25 UTC, larsgsvensson requested changes
I'm not quite sure this addresses Antoine's concern in #575 no 10... @aisaac can you have a look at this?

2018-11-16 16:26 UTC, larsgsvensson approved these changes
Addressing Issue 575 12 OK

2018-11-16 16:28 UTC, larsgsvensson approved these changes
Addressing 575 13 OK

2018-11-16 16:32 UTC, larsgsvensson commented
The fixing of #579, #570, #571 and #572 all relate to profile-ont and not to conneg-by-ap so I don't feel competent to review those. @rob-metalinkage can you have a look at those and then merge if @aisaac is fine with the changes in commit https://github.com/w3c/dxwg/pull/593/commits/798f292f561a7dd4e924e6c49ab93343e98e13f0

2018-11-16 22:31 UTC, merged

2018-11-19 22:02 UTC, aisaac commented
@larsgsvensson indeed I'm mildly convinced with the proposed solution for #575 10. I guess I was not clear enough... I've detailed this in a new comment for #575. Sorry I've missed all these notifications in the overflow of commits and pulls in the past days.