Change short names and explain scope better
w3c/dxwg pull request #599
Opened 2018-11-20 22:36 UTC by rob-metalinkage

I couldnt see any definition in the abstract, but I've reworded to make it more explicit about the scope.

2018-11-21 17:45 UTC, kcoyle requested changes
The definition of profiles ontology does not match my understanding of the ontology. The definition here says: "describes the general pattern of narrowing the scope of a specification" which to me isn't the case. It describes the components of a profile. It doesn't narrow anything and it isn't general - it is specific to profiles. Here's my view:

"The Profile Ontology allows one to describe a profile as a set of one or more resources that fulfill the functions of the profile such as vocabulary definition, input instructions, validation. The ontology also includes the capability to describe a profile's relationship to other files or profiles, such as 'profile of' another profile or vocabulary."

If possible, other changes included here could be allowed to merge, such as those that add "dx-" to the short names.

2018-11-22 06:17 UTC, rob-metalinkage commented
broke the branch. replacing

2018-11-22 06:17 UTC, closed without merging

2018-11-22 17:32 UTC, kcoyle commented
The Profiles Ontology is an RDF vocabulary to describe the resources that define and implement a profile. These resources may be human-readable documents (PDFs, textual documents), vocabularies or ontologies (XSD, RDF),  resources specific to validation tools (SHACL, ShEx, Schematron), or any other files or resources that support the profile. Each resource is defined as having a role that defines its function within the profile.

The ontology also provides for the description of relationships between profiles and the standards to which they conform. Standards in this case can be vocabularies or it can be other profiles from which the described profile is a derivation, expansion, or selection. This ontology provides a standardized, machine readable formalism for describing the context of profiles. The basis of the ontology is a specialization of <code><a href="http://www.dublincore.org/documents/dcmi-terms/#terms-Standard">dct:Standard</a></code>, allowing the use of the <code><a href="http://www.dublincore.org/documents/dcmi-terms/#terms-conformsTo">dct:conformsTo</a></code> predicate to specify conformance to a profile.

Would definitely like @draggett to review - not just this but the entire introduction (just a few paragraphs)

2018-11-22 18:34 UTC, draggett commented
@kcoyle writes:
> The Profiles Ontology is an RDF vocabulary to describe the resources that define and implement a profile.

which begs the question of what is the definition of the term "profile" in this context. I would like to see that given immediately before the definition of "profiles ontology".

2018-11-22 18:59 UTC, draggett commented
Some minor readability tweaks to the second paragraph:
> This ontology also provides for the description of relationships between such profiles and the standards to which they conform. Standards in this case can be vocabularies or it can be other profiles from which the described profile is a derivation, expansion, or selection. This ontology provides a standardized, machine readable formalism for describing the context of profiles. The basis of the ontology is a specialization of dct:Standard, allowing the use of the dct:conformsTo predicate to specify conformance to a profile.