Dcat issue #675 riccardo
w3c/dxwg pull request #750
Opened 2019-02-11 14:58 UTC by riccardoAlbertoni

I have prepared a PR to address @andrea-perego  comments on Identifier issue #675.
In particular, I have 
- mentioned identifier schemes for actors
- added  doi display rec from CrossRef and DataCite and deleting info namespace
- added an  example of locally minted identifier for creator and correspondent ORCID ID

Please @andrea-perego check if these changes meet your expectations, and in case they are not, feel free to suggest or commit further changes.
 
Thanks,

2019-02-14 22:08 UTC, andrea-perego requested changes
Thanks, @riccardoAlbertoni . I created a PR (https://github.com/w3c/dxwg/pull/759) with some proposed revisions - merely editorial.

2019-02-18 14:24 UTC, riccardoAlbertoni commented
@andrea-perego wrote:
>Thanks, @riccardoAlbertoni I created a PR (#759) with some proposed revisions - merely editorial.

Thanks, @andrea-perego,
I have accepted and merged your suggestions in "my" branch.
Could you give your approval so we can ask an editor to merge this with the main DCAT branch?

2019-02-18 21:42 UTC, andrea-perego approved these changes

2019-02-19 10:09 UTC, davebrowning commented
Marked as non substantive for IPR from ash-nazg.

2019-02-19 10:10 UTC, merged