Examples for compression and packaging of distributions
w3c/dxwg pull request #772
Opened 2019-02-21 13:15 UTC by makxdekkers

2019-02-21 13:16 UTC, makxdekkers commented
Hope I did it right this time.

2019-02-22 02:19 UTC, dr-shorthair commented
Thanks Makx - 

1. The example is clean. Could you also put them into index.html, as a new section in Annex D. 
2. Initially I was surprised at this, then I actually looked at the conformsTo link and found a table-schema in JSON - nice. 
    dct:conformsTo <https://mvcr1.opendata.cz/czechpoint/2007.json> ;
    dct:format <http://publications.europa.eu/resource/authority/file-type/CSV> ;

2019-02-22 02:20 UTC, dr-shorthair requested changes
Thanks Makx -

1. The example is clean. Could you also put them into index.html, as a new section in Annex D.
2. Initially I was surprised at this, then I actually looked at the conformsTo link and found a table-schema in JSON - nice.
   dct:conformsTo https://mvcr1.opendata.cz/czechpoint/2007.json ;
   dct:format http://publications.europa.eu/resource/authority/file-type/CSV ;

2019-02-22 13:32 UTC, makxdekkers commented
Included the examples in the main document.

2019-02-22 22:22 UTC, agbeltran commented
Thanks @makxdekkers - at the moment, there is a problem with visualising the examples due to using <> instead of &lt; and &gt; 

https://rawgit.com/w3c/dxwg/dcat-makx-examples-compression&packaging/dcat/index.html#packaged-distribution

2019-02-22 22:31 UTC, agbeltran commented
I've fixed the HTML characters.

2019-02-22 22:32 UTC, agbeltran approved these changes

2019-02-24 05:19 UTC, dr-shorthair approved these changes
Good to go now - I'll merge

2019-02-24 05:20 UTC, merged