Implementing proposal 1 to address #85
w3c/dxwg pull request #807
Opened 2019-03-07 11:09 UTC by andrea-perego

See https://github.com/w3c/dxwg/issues/85#issuecomment-470318218

2019-04-18 08:29 UTC, davebrowning commented
I've moved this back into DCAT CR in the hope we can incorporate it in the CR.  If review indicates we need a longer discussion then we can defer it to Future work again.

2019-04-25 03:19 UTC, dr-shorthair commented
Regarding the spatial proposal - the W3C Geo vocabulary is widely known, so I suggest adding an alternative encoding for `Point` using this.

2019-04-25 03:59 UTC, dr-shorthair commented
Regarding temporal coverage - `dct:PeriodOfTime` is essentially equivalent to `time:ProperInterval`. 
I have formalized this in the same branch.

2019-04-28 10:12 UTC, dr-shorthair requested changes
See #909

2019-05-02 23:31 UTC, dr-shorthair approved these changes

2019-05-02 23:41 UTC, dr-shorthair commented
Additional change needed: example of WKT using a CRS other than WGS84

@andrea-perego in the call this week you mentioned the need for temporal and spatial coverage to also be available for `dcat:Catalog`. This is enabled already because 
```
dcat:Catalog rdfs:subClassOf dcat:Dataset .
```

2019-05-04 12:29 UTC, andrea-perego commented
@dr-shorthair said:

> Additional change needed: example of WKT using a CRS other than WGS84

I will add it.

> @andrea-perego in the call this week you mentioned the need for temporal and spatial coverage to also be available for `dcat:Catalog`. This is enabled already because 
> ```
> dcat:Catalog rdfs:subClassOf dcat:Dataset .
> ```

Indeed. So, I guess we don't have to do anything here.

2019-05-05 16:04 UTC, andrea-perego commented
@dr-shorthair , I made the following revisions:

1. As the SDW BPs already include examples of polygons, points, and bboxes, I revised our own to re-use the SDW BP ones - which notably include an example of a polygon using a CRS different from CRS84.
2. I added the example of a geometry using a CRS different from CRS84 (see previous point)
3. I included map previews for geometries in the examples, to make the WKT strings less cryptic for non-experts, and to give readers an idea of what the geometry is referring to on a map.
4. I carried out a number of editorial fixes

Please have a check, and revise them as you see fit.

Considering the resulting "size" of the part concerning the examples for temporal and spatial coverage, it may be more appropriate to move all this stuff to a separate section - consistently with what done of identifiers, etc.

WDYT? 

BTW, the usage notes of `time:hasBeginning` / `time:hasEnd` may have a typo. Quoting the relevant bit:

> In this context this could be taken to imply that dct:PeriodOfTime is equivalent to the subclass time:ProperInterval

Shouldn't this rather be

> In this context this could be taken to imply that dct:PeriodOfTime is equivalent to time:ProperInterval

2019-05-05 20:28 UTC, andrea-perego commented
@dr-shorthair , I just realised that [Example 48](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-rev-temporal-spatial-coverage/dcat/index.html#ex-service-gsa) includes a bbox encoded in GML.

As we are using WKT in all the other examples, I replaced the GML encoding of the bbox in Example 48 with the corresponding WKT one.

Does this make sense to you? 

NB: Corresponding .ttl file in examples/ folder yet to be updated.

BTW, the bbox in Example 48 provides an additional example of geometry using a CRS different from CRS84.

2019-05-05 21:09 UTC, andrea-perego commented
I realised that we were missing an example of how to specify the coordinate reference system of a dataset.

The way to do this in DCAT has already been show in the SDW Best Practices (see [Example 22](https://www.w3.org/TR/sdw-bp/#ex-crs-dataset-metadata) from [SDW BP8](https://www.w3.org/TR/sdw-bp/#bp-crs)), and documented in the DXWG UCR document ([UC28](https://www.w3.org/TR/dcat-ucr/#ID28)).

I therefore tentatively added via commit https://github.com/w3c/dxwg/pull/807/commits/ad0dc0d1915b49ef4297e4783e405baa05d1254f an example in [Section 8.2.1 (Conformance to a standard)](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-rev-temporal-spatial-coverage/dcat/index.html#quality-conformance-statement), following the relevant SDW BP and DXWG UC28.

2019-05-05 21:18 UTC, andrea-perego commented
@dr-shorthair , in [Example 48](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-rev-temporal-spatial-coverage/dcat/index.html#ex-service-eea), the bbox is specified both with GML and WKT.

Should we drop the former?

2019-05-06 14:07 UTC, andrea-perego commented
@dr-shorthair , about this one:

> @dr-shorthair , in [Example 48](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-rev-temporal-spatial-coverage/dcat/index.html#ex-service-eea), the bbox is specified both with GML and WKT.
> 
> Should we drop the former?

I tentatively commented the GML encoding of the bbox in Ex 48 - see:

https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-rev-temporal-spatial-coverage/dcat/index.html#ex-service-eea

2019-05-07 06:00 UTC, dr-shorthair commented
> Considering the resulting "size" of the part concerning the examples for temporal and spatial coverage, it may be more appropriate to move all this stuff to a separate section - consistently with what done of identifiers, etc.

I've done this, and also consolidated some other temporal examples into new (informative) section.

2019-05-07 06:03 UTC, dr-shorthair commented
I think this is good to go now. Since these are substantive changes, they need approval by DCAT team.

2019-05-07 08:08 UTC, andrea-perego commented
@dr-shorthair said:

> I think this is good to go now. Since these are substantive changes, they need approval by DCAT team.

+1 from me. 

I just added some additional editorial changes, and validated HTML markup - see commit https://github.com/w3c/dxwg/pull/807/commits/d10f88ed7f0e0cb503e5f33e11bddc96d03315a5

2019-05-07 08:41 UTC, davebrowning commented
Sterling work guys

One minor thing: there is still an issue NOTE to #85.

More importantly, I get a http 403 for the Europa.eu link at line 3057?

Apart from that it looks good to me

2019-05-07 08:41 UTC, davebrowning approved these changes

2019-05-07 08:48 UTC, andrea-perego commented
@davebrowning said:

> More importantly, I get a http 403 for the Europa.eu link at line 3057?

Thanks for pointing this out. I think it is a temporary issue, but I will check.

2019-05-07 09:00 UTC, davebrowning commented
@andrea-perego said:
> 
> Thanks for pointing this out. I think it is a temporary issue, but I will check.

Yes, just realised I get the same error from gh-pages...

2019-05-07 09:28 UTC, andrea-perego commented
@davebrowning said:

> One minor thing: there is still an issue NOTE to #85.

Thanks, and I also now realise we have not updated the changelog.

I just made a commit commenting the issue NOTE, and updating the changelog (https://github.com/w3c/dxwg/pull/807/commits/2d8422df94b06c069fa1b046b9be3e5856219461)

2019-05-07 09:53 UTC, dr-shorthair commented
We should also copy all the code fragments/examples into ttl files in https://github.com/w3c/dxwg/tree/gh-pages/dcat/examples

2019-05-07 09:55 UTC, andrea-perego commented
@dr-shorthair said:

> We should also copy all the code fragments/examples into ttl files in https://github.com/w3c/dxwg/tree/gh-pages/dcat/examples

I will take care of that.

2019-05-07 09:59 UTC, andrea-perego commented
BTW, are you all happy with the current geometry examples - build upon the SDW BP ones? 

If yes, I will delete the .png files with the map previews of the original examples.

2019-05-07 10:26 UTC, riccardoAlbertoni commented
> BTW, are you all happy with the current geometry examples - build upon the SDW BP ones?

Yes, I like the section "Time and space". I wonder if we should add the support on representing time and space coverage in the "items" listed in the "Status of This Document".

> If yes, I will delete the .png files with the map previews of the original examples.

In my very modest opinion, the .png files do not make any harm, they might help people not familiar with the concepts such as centroid, BB, etc. Anyway if you think otherwise, I do not object to deleting them

2019-05-07 10:27 UTC, riccardoAlbertoni approved these changes

2019-05-07 12:04 UTC, andrea-perego commented
@riccardoAlbertoni said:

> > If yes, I will delete the .png files with the map previews of the original examples.
> 
> In my very modest opinion, the .png files do not make any harm, they might help people not familiar with the concepts such as centroid, BB, etc. Anyway if you think otherwise, I do not object to deleting them

Just for clarity: the .png files of the current examples will be kept. But we have still the .png files of the old examples, and they are not used any longer. These are the ones I was considering deleted, provided that we don't want to switch back to the original examples.

2019-05-07 12:27 UTC, davebrowning commented
What's used in the document works for me.  Probably less confusing to delete the unused ones, but I don't feel strongly about it.

2019-05-07 12:29 UTC, andrea-perego commented
It's for keeping folders clean from unused / unnecessary files. I have a back-up copy of anything, anyway.

2019-05-07 13:52 UTC, davebrowning commented
I think we're done here.  I'd like to notify this PR (and the underlying issues) in the Plenary agenda for today's meeting as per usual process (to flag up the work), so will merge before then, unless someone shouts.  We can handle any issues arising under a separate PR, hopefully just of editorial nature

2019-05-07 17:06 UTC, merged