Conneg 2pwd fixes
w3c/dxwg pull request #897
Opened 2019-04-15 01:15 UTC by nicholascar

Minor edits to better indicate the requirements for implementation regarding multiple realizations

Removal of some now closed Issues.

2019-04-15 02:27 UTC, rob-metalinkage reviewed
happy to accept - have added a commit with a couple of outstanding grammar issues, and attempt to clarify further that the QSA is a recommended approach , but others are possible, and the scope is derived from the charter.

2019-04-15 02:29 UTC, rob-metalinkage approved these changes

2019-04-15 06:41 UTC, larsgsvensson requested changes

2019-04-15 06:41 UTC, larsgsvensson commented on conneg-by-ap/index.html
> +      reference implementations for each <em>realization</em> are given. Other <em>realizations</em> are considered
We don't have those reference implementations yet, do we? I'd propose to remove that statement until we have actual implementation evidence and until then just say that two reference implementations are _required_ but not _given_.

2019-04-16 06:36 UTC, larsgsvensson approved these changes
Thank you @nicholascar, this reflects what I meant.

2019-04-16 06:39 UTC, merged