Uniforming  the position of editorial note and other minor editorial issues
w3c/dxwg pull request #900
Opened 2019-04-18 14:02 UTC by riccardoAlbertoni

Please consider merging this PR.  It uniforms the position of notes warning about new classes and properties. Now all the notes are at the beginning of the sections related to new properties/classes. 
It also adds some missing fullstops.

2019-04-18 21:29 UTC, andrea-perego requested changes
Proposed changes in PR #902

2019-04-18 21:43 UTC, andrea-perego commented
Diff here:

https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fdxwg%2Fdcat&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fdxwg%2Fdcat-UniformingPositionOfEditorialNoteAndOtherMinorEditorialIssues-riccardo%2Fdcat%2Findex.html

2019-04-19 12:27 UTC, andrea-perego approved these changes
+1 from me. Thanks, @riccardoAlbertoni

2019-04-20 04:33 UTC, dr-shorthair approved these changes

2019-04-20 04:33 UTC, merged