Update index.html
w3c/dxwg pull request #994
Opened 2019-07-13 06:56 UTC by larsgsvensson

Changed "Dublin Core Terms" to "DCMI Metadata Terms"
Resolves #992

2019-07-14 14:21 UTC, nicholascar approved these changes

2019-07-15 01:11 UTC, rob-metalinkage requested changes
I actually removed this section in PR #991 as the DCMI folk dont seem to have a consistent statement about  what a profile actually does

2019-07-15 04:42 UTC, nicholascar commented
I've merged which means essentially pulling Rob's complete removal of DCT over the top of Lars' rewriting of DCT so no there's no DCT in this paragraph. Rob please OK this.

2019-07-15 05:39 UTC, rob-metalinkage approved these changes

2019-07-24 03:32 UTC, merged